apiVersion: apps/v1
kind: Deployment
metadata:
  name: { { include "reservation-service.fullname" . } }
  labels:
    app: { { include "reservation-service.name" . } }
spec:
  replicas: { { .Values.replicaCount } }
  selector:
    matchLabels:
      app: { { include "reservation-service.name" . } }
  template:
    metadata:
      labels:
        app: { { include "reservation-service.name" . } }
    spec:
      containers:
        - name: reservation
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: { { .Values.image.pullPolicy } }
          ports:
            - containerPort: { { .Values.service.targetPort } }
              name: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
