{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "rating-service.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: minikube.local
      http:
        paths:
          - path: /rating
            pathType: Prefix
            backend:
              service:
                name: {{ include "rating-service.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}
