apiVersion: v1
kind: Secret
metadata:
  name: hotelier-secrets
  namespace: hotelier
type: Opaque
data:
  jwt__key: qR7tYxFm2X8W5yO0L8tE3Zs9eVVj9u4cQ7xN1wT2pK6rP0uH3M5bY8nA1zD4kV9R
  rabbitmq__password: Zp8mQw3Tn9Vx2sLk7Rj4HbYt
