replicaCount: 1

image:
  repository: pikaac/availability-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 80

resources: {}

ingress:
  enabled: true
  host: "minikube.local"
  path: "/availability"

serviceMonitor:
  enabled: true
  interval: 15s
