global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "availability-service"
    static_configs:
      - targets: ["host.docker.internal:5001"]

  - job_name: "accommodation-service"
    static_configs:
      - targets: ["host.docker.internal:5002"]

  - job_name: "identity-service"
    static_configs:
      - targets: ["host.docker.internal:5003"]

  - job_name: "notification-service"
    static_configs:
      - targets: ["host.docker.internal:5004"]

  - job_name: "rating-service"
    static_configs:
      - targets: ["host.docker.internal:5005"]

  - job_name: "reservation-service"
    static_configs:
      - targets: ["host.docker.internal:5006"]

  - job_name: "search-service"
    static_configs:
      - targets: ["host.docker.internal:5007"]

  - job_name: "cdn-service"
    static_configs:
      - targets: ["host.docker.internal:5008"]

  - job_name: "docker"
    static_configs:
      - targets: ["host.docker.internal:8080"]

  - job_name: "node"
    static_configs:
      - targets: ["host.docker.internal:9100"]

  - job_name: "postgres"
    static_configs:
      - targets: ["host.docker.internal:5432"]

  - job_name: "mongo"
    static_configs:
      - targets: ["host.docker.internal:27017"]
