apiVersion: v1
kind: Service
metadata:
  name: { { include "cdn-service.fullname" . } }
  labels:
    app: { { include "cdn-service.name" . } }
spec:
  type: { { .Values.service.type } }
  selector:
    app: { { include "cdn-service.name" . } }
  ports:
    - name: http
      port: { { .Values.service.port } }
      targetPort: { { .Values.service.targetPort } }
